service: pokeguesser-api
app: pokeguesser
org: talbotp

frameworkVersion: '2'

plugins: 
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3030

provider:
  name: aws
  runtime: python3.8
  stage: prod 
  httpApi:
    cors:
      allowedOrigins:
        - https://www.pokeguesser.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET

functions:
  guess:
    handler: src/guess.handler
    events:
      - httpApi:
          path: /guess
          method: GET
